const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Behaviors.Fade,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Acts.SetHAlign,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Gamesettings_Event65_Act5,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.JavaScriptInEvents.Gamesettings_Event67_Act7,
		C3.JavaScriptInEvents.Gamesettings_Event68_Act3,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.JavaScriptInEvents.Gamesettings_Event99_Act6,
		C3.JavaScriptInEvents.Gamesettings_Event100_Act15,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.JavaScriptInEvents.Gamesettings_Event107_Act14,
		C3.JavaScriptInEvents.Gamesettings_Event110_Act14,
		C3.Plugins.Browser.Acts.LockOrientation,
		C3.Plugins.Audio.Acts.Preload
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{Touch: 0},
	{AddBg: 0},
	{BackGround: 0},
	{MainBg: 0},
	{WellDone1: 0},
	{ScoreBg: 0},
	{Bullet: 0},
	{Snow: 0},
	{Sine: 0},
	{Logo: 0},
	{WellDone: 0},
	{BackButton: 0},
	{HelpButton: 0},
	{InfoButton: 0},
	{Menu: 0},
	{No_button: 0},
	{Pause: 0},
	{Paused: 0},
	{Play: 0},
	{Restart: 0},
	{Sounds: 0},
	{Yes_Button: 0},
	{MiniBalloon1: 0},
	{MiniBalloon2_0: 0},
	{MiniBalloon2_1: 0},
	{MiniBalloon2_2: 0},
	{MiniBalloon2_3: 0},
	{MiniBalloon3: 0},
	{MiniBalloon4: 0},
	{MiniBalloon5: 0},
	{MiniBalloon6: 0},
	{Balloon1: 0},
	{Balloon2: 0},
	{Balloon3: 0},
	{Balloon4: 0},
	{Balloon5: 0},
	{Balloon6: 0},
	{Balloon1FontTxt: 0},
	{Balloon3FontTXt: 0},
	{Balloon4FontTxt: 0},
	{Balloon5FontTxt: 0},
	{Balloon6FontTxt: 0},
	{InfoHelpText: 0},
	{PausedText: 0},
	{ScoreFontText: 0},
	{ScoreText: 0},
	{ScoreText2: 0},
	{Pin: 0},
	{Text_Add: 0},
	{WeldoneText: 0},
	{Fade: 0},
	{Balloon1Crash: 0},
	{Balloon2Crash: 0},
	{Balloon3Crash: 0},
	{Balloon4Crash: 0},
	{Balloon5Crash: 0},
	{Balloon6Crash: 0},
	{Collision: 0},
	{logo1: 0},
	{Score: 0},
	{Sound: 0},
	{Balloon: 0},
	{LastScore: 0},
	{HighScore: 0},
	{GameName: 0},
	{rv_ad_enabled: 0},
	{rv_popup: 0},
	{isInfo: 0},
	{TriggerPopupValue: 0},
	{DOMAIN_SCORES: 0},
	{isDisplayAd: 0},
	{isBannerAd: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	AddBg: class extends self.ISpriteInstance {},
	BackGround: class extends self.ISpriteInstance {},
	MainBg: class extends self.ISpriteInstance {},
	WellDone1: class extends self.ISpriteInstance {},
	ScoreBg: class extends self.ISpriteInstance {},
	Snow: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	WellDone: class extends self.ISpriteInstance {},
	BackButton: class extends self.ISpriteInstance {},
	HelpButton: class extends self.ISpriteInstance {},
	InfoButton: class extends self.ISpriteInstance {},
	Menu: class extends self.ISpriteInstance {},
	No_button: class extends self.ISpriteInstance {},
	Pause: class extends self.ISpriteInstance {},
	Paused: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	Restart: class extends self.ISpriteInstance {},
	Sounds: class extends self.ISpriteInstance {},
	Yes_Button: class extends self.ISpriteInstance {},
	MiniBalloon1: class extends self.ISpriteInstance {},
	MiniBalloon2_0: class extends self.ISpriteInstance {},
	MiniBalloon2_1: class extends self.ISpriteInstance {},
	MiniBalloon2_2: class extends self.ISpriteInstance {},
	MiniBalloon2_3: class extends self.ISpriteInstance {},
	MiniBalloon3: class extends self.ISpriteInstance {},
	MiniBalloon4: class extends self.ISpriteInstance {},
	MiniBalloon5: class extends self.ISpriteInstance {},
	MiniBalloon6: class extends self.ISpriteInstance {},
	Balloon1: class extends self.ISpriteInstance {},
	Balloon2: class extends self.ISpriteInstance {},
	Balloon3: class extends self.ISpriteInstance {},
	Balloon4: class extends self.ISpriteInstance {},
	Balloon5: class extends self.ISpriteInstance {},
	Balloon6: class extends self.ISpriteInstance {},
	Balloon1FontTxt: class extends self.ITextInstance {},
	Balloon3FontTXt: class extends self.ITextInstance {},
	Balloon4FontTxt: class extends self.ITextInstance {},
	Balloon5FontTxt: class extends self.ITextInstance {},
	Balloon6FontTxt: class extends self.ITextInstance {},
	InfoHelpText: class extends self.ITextInstance {},
	PausedText: class extends self.ITextInstance {},
	ScoreFontText: class extends self.ITextInstance {},
	ScoreText: class extends self.ITextInstance {},
	ScoreText2: class extends self.ITextInstance {},
	Text_Add: class extends self.ITextInstance {},
	WeldoneText: class extends self.ITextInstance {},
	Balloon1Crash: class extends self.ISpriteInstance {},
	Balloon2Crash: class extends self.ISpriteInstance {},
	Balloon3Crash: class extends self.ISpriteInstance {},
	Balloon4Crash: class extends self.ISpriteInstance {},
	Balloon5Crash: class extends self.ISpriteInstance {},
	Balloon6Crash: class extends self.ISpriteInstance {},
	Collision: class extends self.ISpriteInstance {},
	logo1: class extends self.ISpriteInstance {}
}